# Generated by Django 5.2.8 on 2025-11-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='contact_number',
        ),
    ]
