# Generated by Django 5.2.8 on 2025-11-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_studentprofile_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='middle_name',
        ),
    ]
