# Generated by Django 5.2.8 on 2025-11-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_studentprofile_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_picture',
        ),
    ]
