# Generated by Django 5.2.8 on 2025-11-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='header_picture',
            field=models.ImageField(blank=True, null=True, upload_to='org_header_pics/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='org_profile_pics/'),
        ),
    ]
