# Generated by Django 5.2.8 on 2025-11-25 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='followed_organizations',
        ),
        migrations.AddField(
            model_name='organization',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
