# Generated by Django 5.2.8 on 2025-11-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_studentprofile_followed_organizations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='officers',
        ),
        migrations.DeleteModel(
            name='OrganizationOfficer',
        ),
    ]
