# Generated by Django 5.2.8 on 2025-11-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_organization_officers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_level',
            field=models.CharField(choices=[('UNIVERSITY', 'University'), ('COLLEGE', 'College'), ('DEPARTMENT', 'Department'), ('ORGANIZATION', 'Organization')], default='ORGANIZATION', max_length=20),
        ),
    ]
