# Generated by Django 5.2.8 on 2025-11-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='parent_event',
        ),
    ]
