# Generated by Django 5.2.8 on 2025-11-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_event_end_datetime_alter_event_start_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_officer',
        ),
    ]
