# Generated by Django 5.2.8 on 2025-11-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Council'), (2, 'College'), (3, 'Department'), (4, 'Student Organization')]),
        ),
    ]
